/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as OrdinanzaDemolizioneRouteImport } from './routes/ordinanza-demolizione'
import { Route as OptinRouteImport } from './routes/optin'
import { Route as EspropriIndennitaRouteImport } from './routes/espropri-indennita'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as IndexRouteImport } from './routes/index'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdinanzaDemolizioneRoute = OrdinanzaDemolizioneRouteImport.update({
  id: '/ordinanza-demolizione',
  path: '/ordinanza-demolizione',
  getParentRoute: () => rootRouteImport,
} as any)
const OptinRoute = OptinRouteImport.update({
  id: '/optin',
  path: '/optin',
  getParentRoute: () => rootRouteImport,
} as any)
const EspropriIndennitaRoute = EspropriIndennitaRouteImport.update({
  id: '/espropri-indennita',
  path: '/espropri-indennita',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/espropri-indennita': typeof EspropriIndennitaRoute
  '/optin': typeof OptinRoute
  '/ordinanza-demolizione': typeof OrdinanzaDemolizioneRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/espropri-indennita': typeof EspropriIndennitaRoute
  '/optin': typeof OptinRoute
  '/ordinanza-demolizione': typeof OrdinanzaDemolizioneRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking': typeof BookingRoute
  '/espropri-indennita': typeof EspropriIndennitaRoute
  '/optin': typeof OptinRoute
  '/ordinanza-demolizione': typeof OrdinanzaDemolizioneRoute
  '/quiz': typeof QuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/espropri-indennita'
    | '/optin'
    | '/ordinanza-demolizione'
    | '/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking'
    | '/espropri-indennita'
    | '/optin'
    | '/ordinanza-demolizione'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/booking'
    | '/espropri-indennita'
    | '/optin'
    | '/ordinanza-demolizione'
    | '/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingRoute: typeof BookingRoute
  EspropriIndennitaRoute: typeof EspropriIndennitaRoute
  OptinRoute: typeof OptinRoute
  OrdinanzaDemolizioneRoute: typeof OrdinanzaDemolizioneRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordinanza-demolizione': {
      id: '/ordinanza-demolizione'
      path: '/ordinanza-demolizione'
      fullPath: '/ordinanza-demolizione'
      preLoaderRoute: typeof OrdinanzaDemolizioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optin': {
      id: '/optin'
      path: '/optin'
      fullPath: '/optin'
      preLoaderRoute: typeof OptinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espropri-indennita': {
      id: '/espropri-indennita'
      path: '/espropri-indennita'
      fullPath: '/espropri-indennita'
      preLoaderRoute: typeof EspropriIndennitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingRoute: BookingRoute,
  EspropriIndennitaRoute: EspropriIndennitaRoute,
  OptinRoute: OptinRoute,
  OrdinanzaDemolizioneRoute: OrdinanzaDemolizioneRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
